---

- hosts: all
  become: true
  become_method: sudo

  vars:
    aws_user: vagrant # (Linux User who should use aws cli)

  pre_tasks:
  - name: Include custom_vars.yml
    include_vars:
      file: custom_vars.yml

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.awscli
  - andrelohmann.terraform
  - andrelohmann.kubectl
  - andrelohmann.kops

...
